# Generated by Django 5.0.6 on 2024-05-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_us_description',
            field=models.TextField(verbose_name='Info about the company.'),
        ),
        migrations.AlterField(
            model_name='about',
            name='contacts_string',
            field=models.TextField(verbose_name='Info on how to contact us.'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
