# Generated by Django 5.0.6 on 2024-05-31 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_service_service_type_doctorprofile_appoinment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service_type'),
        ),
    ]
