# Generated by Django 5.0.6 on 2024-05-31 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_appoinment_doctor_id_service_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.doctorprofile'),
        ),
    ]
